package genlandmarknames

// GenitivePhraseAdjPos returns a genitive phrase adjective for peaceful areas.
var GenitivePhraseAdjPos = []string{
	"loving",
	"blessed",
	"heroic",
	"brave",
	"noble",
	"valiant",
	"virtuous",
	"pure",
	"sacred",
	"divine",
	"benevolent",
	"kind",
	"gentle",
	"calm",
	"peaceful",
	"tranquil",
	"serene",
	"eternal",
	"immortal",
	"everlasting",
	"undying",
}

// GenitivePhraseAdjNeg is a list of prefixes suitable for dangerous areas.
var GenitivePhraseAdjNeg = []string{
	"cursed",
	"forsaken",
	"forbidden",
	"lost",
	"abandoned",
	"unknown",
	"doomed",
	"haunted",
	"dark",
	"evil",
	"chaotic",
	"mad",
	"lost",
	"lost souls",
	"the dead",
	"the damned",
	"the cursed",
	"the forsaken",
	"the lost",
	"the forgotten",
	"the abandoned",
	"the unknown",
	"the doomed",
}

// GenitivePhraseAdjNegWaterStill returns a genitive phrase adjective for lakes, ponds, and swamps.
var GenitivePhraseAdjNegWaterStill = []string{
	"lost",
	"petrified",
	"forgotten",
	"sunken",
	"abandoned",
	"flushed",
	"rotten",
	"decaying",
	"rotting",
	"sinking",
	"dark",
	"black",
	"murky",
	"deep",
	"bottomless",
}

// GenitivePhraseAdjNegWaterFlowing returns a genitive phrase adjective for rivers.
var GenitivePhraseAdjNegWaterFlowing = []string{
	"drowned",
	"lost",
	"sunken",
	"forgotten",
	"abandoned",
	"flushed",
	"rotten",
	"decaying",
	"rotting",
	"sinking",
}

// GenitivePhraseAdjThicket returns a genitive phrase adjective for forests, woods, and thickets.
var GenitivePhraseAdjThicket = []string{
	"dark",
	"shadowy",
	"twisted",
	"thorny",
	"cutting",
	"forsaken",
	"rotten",
	"lost",
	"petrified",
	"forgotten",
	"abandoned",
	"consumed",
	"buried",
	"fallen",
	"buried",
	"defeated",
	"covered",
}

// GenitivePhraseSubject is a list of suffixes suitable for dangerous areas.
// TODO: Split this up into groups (people, things, abstract concepts).
var GenitivePhraseSubject = []string{
	"hope",
	"souls",
	"fate",
	"dreams",
	"love",
	"life",
	"joy",
	"peace",
	"riches",
	"wealth",
	"power",
	"glory",
	"victory",
	"triumph",
	"success",
	"prosperity",
	"fortune",
	"luck",
	"health",
	"strength",
	"wisdom",
	"knowledge",
	"truth",
	"justice",
	"freedom",
	"liberty",
	"serenity",
	"calm",
	"tranquility",
	"corpses",
	"heroes",
	"villains",
	"princes",
	"princesses",
	"queens",
	"kings",
	"emperors",
	"empresses",
	"lords",
	"ladies",
	"knights",
	"lovers",
	"warriors",
	"mages",
	"witches",
	"witchers",
	"druids",
	"monks",
	"nuns",
	"priests",
	"priestesses",
	"paladins",
	"clerics",
	"rogues",
	"thieves",
	"assassins",
	"mercenaries",
	"adventurers",
	"explorers",
}
